Repository jdi-testing/test-site, pull requests merged in 2023-01, with the labels that each got.

#316 4232 add elements bottom navigation
  components/bottom_navigation/FixedBottomNavigation.vue
  pages/Bottom-Navigation.vue
Labels: add element

#317 4589 add element forms
  components/form_inputs/forms/SubmitForm.vue
  pages/Forms.vue
Labels: add element

#318 autocompletes fix
  components/form_inputs/autocompletes/AutocompleteAPISearch.vue
  components/form_inputs/autocompletes/AutocompleteAsyncItems.vue
  components/form_inputs/autocompletes/AutocompleteFilter.vue
  components/form_inputs/autocompletes/AutocompleteFunctionality.vue
  components/form_inputs/autocompletes/AutocompleteSlots.vue
  components/form_inputs/autocompletes/AutocompleteStyle.vue
Labels: add element

#319 Task 4705: Add elements on the test-site DataIterators
  components/tables/data_iterators/LoadingText.vue
  components/tables/data_iterators/NoDataText.vue
  components/tables/data_iterators/NoResultsText.vue
  pages/Data-Iterators.vue
Labels: add element, TestSite, Vuetify

#320 fixed input alpha value issue in color pickers on the range sliders page
  components/form_inputs/range_sliders/ColorRangerSlider.vue
  components/form_inputs/sliders/AdjustableSlider.vue
Labels: TestSite, Vuetify
